version: "3.8"

services:
  nextmerce-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Neon PostgreSQL Database
      - DATABASE_URL=${DATABASE_URL}

      # NextAuth
      - NEXT_AUTH_SECRET=${NEXT_AUTH_SECRET}
      - NEXT_AUTH_URL=${NEXT_AUTH_URL}

      # Site Configuration
      - SITE_URL=${SITE_URL}

      # Sanity CMS (Cloud)
      - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
      - NEXT_PUBLIC_SANITY_PROJECT_TITLE=${NEXT_PUBLIC_SANITY_PROJECT_TITLE}
      - SANITY_PROJECT_API_TOKEN=${SANITY_PROJECT_API_TOKEN}
      - SANITY_HOOK_SECRET=bd42VNVuyMt2CeV1adEQkxInkhMDm/EPXf7+uAFsFhk=

      # Admin
      - ADMIN_EMAILS=${ADMIN_EMAILS}

      # Revalidation
      - NEXT_PUBLIC_REVALIDATE_SECRET=${NEXT_PUBLIC_REVALIDATE_SECRET}
      - REVALIDATE_SECRET=${REVALIDATE_SECRET}

      # Algolia Search (Cloud)
      - NEXT_PUBLIC_ALGOLIA_PROJECT_ID=${NEXT_PUBLIC_ALGOLIA_PROJECT_ID}
      - NEXT_PUBLIC_ALGOLIA_API_KEY=${NEXT_PUBLIC_ALGOLIA_API_KEY}
      - NEXT_PUBLIC_ALGOLIA_INDEX=${NEXT_PUBLIC_ALGOLIA_INDEX}

      # Stripe Payment (Cloud)
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SHIPPING_RATE_ID=${STRIPE_SHIPPING_RATE_ID}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
